[service]
name = "monolith-worker"

[runtime]
kind = "rust"

[headless]

[resources.single-node]
cpu = 250
# See SVC-3413
memory = 512

[resources.distributed]
cpu = 1000
memory = 1024

[cockroachdb]
min-connections = 8

